cc_library(
    name = "mesh_utils",
    srcs = ["shape_renderer.cpp"],
    hdrs = ["shape_renderer.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/core:base",
        "//third_party/filament",
    ],
)
